### ISSUE TITLE
Nintendogs + Cats: hang on start

### ISSUE THREAD

**Issue by acnleditor2** [acnleditor2/citra#56]
With Subv:releasemutex, fatal error
With huwpascoe:chain, crash

**Comment by Subv** [comment]
Do you have a log? This issue doesn't tell us anything without a log.

**Comment by acnleditor2** [comment]
on my build or official?

**Comment by acnleditor2** [comment]
@Subv my build (on new builds releasemutex & chain are reverted):
[   0.000000] Common.Filesystem <Info> common/file_util.cpp:GetUserPath:695: Using the local user directory
[   0.496646] Loader <Warning> core/loader/loader.cpp:GetLoader:137: File C:/Users/79869/Pictures/clear.fi/Pinned/0/tl/head/tl.3ds has a different type than its extension.
[   2.278918] Frontend <Info> citra_qt/main.cpp:BootGame:551: Citra starting...
[   2.326533] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:238: Loaded NCCH C:\Users\79869\Pictures\clear.fi\Pinned\0\tl\head/user/nand/00000000000000000000000000000000/title/0004009b/00010202/content/00000000.app is tainted, application behavior may not be as expected!
[   2.327689] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:238: Loaded NCCH C:\Users\79869\Pictures\clear.fi\Pinned\0\tl\head/user/nand/00000000000000000000000000000000/title/0004009b/00010402/content/00000000.app is tainted, application behavior may not be as expected!
[   2.328513] Service.FS <Warning> core/file_sys/ncch_container.cpp:LoadOverrides:238: Loaded NCCH C:\Users\79869\Pictures\clear.fi\Pinned\0\tl\head/user/nand/00000000000000000000000000000000/title/000400db/00010302/content/00000000.app is tainted, application behavior may not be as expected!
[   2.335403] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:488: GL_VERSION: 3.3.0 - Build 21.20.16.4534
[   2.336188] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:489: GL_VENDOR: Intel
[   2.336331] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:490: GL_RENDERER: Intel(R) HD Graphics 620
[   2.342062] Loader <Info> core/loader/ncch.cpp:Load:159: Program ID: 0004000000030C00
[   2.342608] Service.FS <Warning> core/file_sys/ncch_container.cpp:OpenFile:107: Failed to open C:\Users\79869\Pictures\clear.fi\Pinned\0\tl\head/user/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e/00030c00/content/00000000.app
[   2.376141] Service.CFG <Info> core/hle/service/cfg/cfg.cpp:SetPreferredRegionCode:613: Preferred region code set to 2
[   3.021536] Service.SRV <Warning> core/hle/service/sm/srv.cpp:RegisterClient:48: (STUBBED) called
[   3.022289] Service.SRV <Warning> core/hle/service/sm/srv.cpp:EnableNotification:70: (STUBBED) called
[   3.025381] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetLockHandle:431: (STUBBED) called handle=0x00040009 applet_attributes=0x00000000
[   3.050083] Service.APT <Warning> core/hle/service/apt/apt.cpp:NotifyToWait:408: (STUBBED) app_id=768
[   3.053737] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:733: (STUBBED) called command=0x00000007, input_size=0x00000004, output_size=0x00000001, input_addr=0x0FFFFF78, output_addr=0x0FFFFF48
[   3.055908] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:733: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFF4C, output_addr=0x0FFFFF48
[   3.057967] Service.NDM <Warning> core/hle/service/ndm/ndm.cpp:SuspendDaemons:89: (STUBBED) daemon_bit_mask=0x00000009
[   3.121185] Service.GSP <Warning> core/hle/service/gsp_gpu.cpp:AcquireRight:702: called
[   3.122660] Service.GSP <Warning> core/hle/service/gsp_gpu.cpp:RegisterInterruptRelayQueue:397: called, flags=0x00000001
[   3.370488] Service.FS <Error> core/hle/service/fs/fs_user.cpp:OpenArchive:464: failed to get a handle for archive archive_id=0x00000004 archive_path=[Empty]
[   3.395896] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:733: (STUBBED) called command=0x00000007, input_size=0x00000004, output_size=0x00000001, input_addr=0x0FFFFAB8, output_addr=0x0FFFFA88
[   3.398804] Service.APT <Warning> core/hle/service/apt/apt.cpp:AppletUtility:733: (STUBBED) called command=0x00000004, input_size=0x00000001, output_size=0x00000001, input_addr=0x0FFFFA94, output_addr=0x0FFFFA90
[   3.405746] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:146: (STUBBED) called, notification_id=0x207
[   3.407238] Service.SRV <Warning> core/hle/service/sm/srv.cpp:Subscribe:146: (STUBBED) called, notification_id=0x209
[   3.416483] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:InitializeSession:40: (STUBBED) unk_param=0x0000000000000000, translation=0x00000020, unk_param4=0x00000000
[   3.419797] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:GetTaskIdList:229: (STUBBED) called
[   3.420688] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:ReceiveProperty:397: (STUBBED) unk_param1=0x00000035, buff_size=0x00000002, translation=0x0000002C, buff_addr=0x145917E0
[   3.421797] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:ReceiveProperty:397: (STUBBED) unk_param1=0x00000036, buff_size=0x00000400, translation=0x0000400C, buff_addr=0x145917E8
[   3.423512] Service.BOSS <Warning> core/hle/service/boss/boss.cpp:GetOptoutFlag:162: output_flag=0
[   3.445001] Kernel.SVC <Warning> core/hle/svc.cpp:CreateMemoryBlock:1175: called addr=0x007CB000
[   3.445885] Service.MIC <Warning> core/hle/service/mic_u.cpp:MapSharedMem:62: called, size=0x1000, mem_handle=0x00118031
[   3.447090] Service.MIC <Warning> core/hle/service/mic_u.cpp:GetGain:194: (STUBBED) called
[   3.447906] Service.MIC <Warning> core/hle/service/mic_u.cpp:SetGain:179: (STUBBED) called, mic_gain=43
[   3.448519] Service.MIC <Warning> core/hle/service/mic_u.cpp:SetPower:209: (STUBBED) called, mic_power=1
[   3.456424] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:LoadComponent:148: Firmware hash: 0x7fdb265b3e9d36d9
[   3.456806] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:LoadComponent:152: Structures hash: 0x3f02d76b56ccedc5
[   3.458459] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:LoadComponent:157: (STUBBED) called size=0xBDCE, prog_mask=0x000000FF, data_mask=0x001200FF, buffer=0x00792930
[   3.460294] Service.DSP <Info> core/hle/service/dsp_dsp.cpp:RegisterInterruptEvents:248: Registered type=2, pipe=2, event_handle=0x00128033
[   3.461272] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:GetSemaphoreEventHandle:174: (STUBBED) called
[   3.462059] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphoreMask:469: (STUBBED) called mask=0x00002000
[   3.462926] Audio.DSP <Info> audio_core/hle/pipe.cpp:PipeWrite:134: Application has requested initialization of DSP hardware
[   3.464670] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphore:271: (STUBBED) called
[   3.470182] Service.DSP <Warning> core/hle/service/dsp_dsp.cpp:SetSemaphore:271: (STUBBED) called
[   3.502567] Kernel.SVC <Error> core/hle/svc.cpp:CreateThread:784: Newly created thread must run in the SysCore (Core1), unimplemented.
